save_folder: ./checkpoints
data:
  sequence_col: protein
  train_data_path: "./opencrispr-repro-main/data/crispr_train_test.csv" 
  val_data_path: "./opencrispr-repro-main/data/crispr_val_test.csv"
  label_col: null 
  batch_size: 8
  num_workers: 2
model:
  name: progen2
  path: base
training:
  learning_rate: 0.0001
  weight_decay: 0.000001
  warmup_steps: 1000
  train_steps: 10000
  total_lr_decay_factor: 0.2
  gradient_clipping_threshold: 1.0
save_interval_steps: 1000